# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /afs/inf.ed.ac.uk/user/s20/s2003300/Desktop/Coursework/CARD/prac2/src/ip/cpu_clock_gen/cpu_clock_gen.xci
# IP: The module: 'cpu_clock_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/inf.ed.ac.uk/user/s20/s2003300/Desktop/Coursework/CARD/prac2/src/ip/cpu_clock_gen/cpu_clock_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_clock_gen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /afs/inf.ed.ac.uk/user/s20/s2003300/Desktop/Coursework/CARD/prac2/src/ip/cpu_clock_gen/cpu_clock_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_clock_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /afs/inf.ed.ac.uk/user/s20/s2003300/Desktop/Coursework/CARD/prac2/src/ip/cpu_clock_gen/cpu_clock_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_clock_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /afs/inf.ed.ac.uk/user/s20/s2003300/Desktop/Coursework/CARD/prac2/src/ip/cpu_clock_gen/cpu_clock_gen.xci
# IP: The module: 'cpu_clock_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/inf.ed.ac.uk/user/s20/s2003300/Desktop/Coursework/CARD/prac2/src/ip/cpu_clock_gen/cpu_clock_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_clock_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /afs/inf.ed.ac.uk/user/s20/s2003300/Desktop/Coursework/CARD/prac2/src/ip/cpu_clock_gen/cpu_clock_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_clock_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /afs/inf.ed.ac.uk/user/s20/s2003300/Desktop/Coursework/CARD/prac2/src/ip/cpu_clock_gen/cpu_clock_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_clock_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
