# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /afs/inf.ed.ac.uk/user/s20/s2003300/Desktop/Coursework/CARD/prac2/src/constraints/top.xdc

# XDC: /afs/inf.ed.ac.uk/user/s20/s2003300/Desktop/Coursework/CARD/prac2/src/constraints/timing.xdc

# IP: /afs/inf.ed.ac.uk/user/s20/s2003300/Desktop/Coursework/CARD/prac2/src/ip/rgb2dvi_0/rgb2dvi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rgb2dvi_0 || ORIG_REF_NAME==rgb2dvi_0} -quiet] -quiet

# IP: /afs/inf.ed.ac.uk/user/s20/s2003300/Desktop/Coursework/CARD/prac2/src/ip/video_clock_gen/video_clock_gen.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==video_clock_gen || ORIG_REF_NAME==video_clock_gen} -quiet] -quiet

# IP: /afs/inf.ed.ac.uk/user/s20/s2003300/Desktop/Coursework/CARD/prac2/src/ip/cpu_clock_gen/cpu_clock_gen.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_clock_gen || ORIG_REF_NAME==cpu_clock_gen} -quiet] -quiet
