webtalk_init -webtalk_dir /afs/inf.ed.ac.uk/user/s20/s2003300/Desktop/Coursework/CARD/prac0/project_0/project_0.sim/sim_1/behav/xsim/xsim.dir/tbexor_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Sep 25 22:32:02 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e3c7c93e-97a6-4f67-96ae-e92d9eaaa342" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "70434c5074b24d128e02fb18a18041ff" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Scientific" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Scientific Linux release 7.6 (Nitrogen)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3348.437 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "150 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124512_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3066269753 -regid "" -xml /afs/inf.ed.ac.uk/user/s20/s2003300/Desktop/Coursework/CARD/prac0/project_0/project_0.sim/sim_1/behav/xsim/xsim.dir/tbexor_behav/webtalk/usage_statistics_ext_xsim.xml -html /afs/inf.ed.ac.uk/user/s20/s2003300/Desktop/Coursework/CARD/prac0/project_0/project_0.sim/sim_1/behav/xsim/xsim.dir/tbexor_behav/webtalk/usage_statistics_ext_xsim.html -wdm /afs/inf.ed.ac.uk/user/s20/s2003300/Desktop/Coursework/CARD/prac0/project_0/project_0.sim/sim_1/behav/xsim/xsim.dir/tbexor_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
